### ISSUE TITLE
Constituency layer Edge Head not generated

### ISSUE THREAD

**Issue by jofatmofn** [ixa-ehu/pynaf#2]
To add_constituency_tree method, whatever value I provide for head attribute of edge, it was simply getting ignored.

Not sure, if this is the right fix, but the following change, makes it working:
FROM
```
    edge = etree.SubElement(tree, CONSTITUENCY_EDGES, {
        CONSTITUENCY_EDGE_ID_ATTRIBUTE: edge[0],
        CONSTITUENCY_EDGE_FORM_ATTRIBUTE: edge[1],
        CONSTITUENCY_EDGE_TO_ATTRIBUTE: edge[2]})
    if len(edge) > 3:
        edge[CHUNK_HEAD_ATTRIBUTE] = edge[3]

```
TO

    if len(edge) > 3:
        etree.SubElement(tree, self.CONSTITUENCY_EDGES, {
            self.CONSTITUENCY_EDGE_ID_ATTRIBUTE: edge[0],
            self.CONSTITUENCY_EDGE_FORM_ATTRIBUTE: edge[1],
            self.CONSTITUENCY_EDGE_TO_ATTRIBUTE: edge[2],
            self.CHUNK_HEAD_ATTRIBUTE: edge[3]
            })
    else:
        etree.SubElement(tree, self.CONSTITUENCY_EDGES, {
            self.CONSTITUENCY_EDGE_ID_ATTRIBUTE: edge[0],
            self.CONSTITUENCY_EDGE_FORM_ATTRIBUTE: edge[1],
            self.CONSTITUENCY_EDGE_TO_ATTRIBUTE: edge[2]
            })

**Comment by josubg** [comment]
Thanks.  I just pushed a shorter version of your fix. If you can check whether the fix is correct,  It would be awesome .

```
attrib = {
                self.CONSTITUENCY_EDGE_ID_ATTRIBUTE: edge[0],
                self.CONSTITUENCY_EDGE_FORM_ATTRIBUTE: edge[1],
                self.CONSTITUENCY_EDGE_TO_ATTRIBUTE: edge[2]}
            if len(edge) > 3:
                attrib[self.CHUNK_HEAD_ATTRIBUTE] = edge[3]

            etree.SubElement(tree, self.CONSTITUENCY_EDGES, attrib)
```

**Comment by jofatmofn** [comment]
Tested the fix. It works. Thanks for taking this up.
Regards.

On Thu Jun 15 2017 01:12:41 GMT+0530 (India Standard Time), Josu B <notifications@github.com> wrote:


Thanks. I just pushed a shorter version of your fix. If you can check whether the fix is correct, It would be awesome .
attrib = {
                self.CONSTITUENCY_EDGE_ID_ATTRIBUTE: edge[0],
                self.CONSTITUENCY_EDGE_FORM_ATTRIBUTE: edge[1],
                self.CONSTITUENCY_EDGE_TO_ATTRIBUTE: edge[2]}
            if len(edge) > 3:
                attrib[self.CHUNK_HEAD_ATTRIBUTE] = edge[3]

            etree.SubElement(tree, self.CONSTITUENCY_EDGES, attrib)
