### ISSUE TITLE
Raw Layer

### ISSUE THREAD

**Issue by jofatmofn** [ixa-ehu/pynaf#3]
This is more a feature request than an issue, as the specification states that the Raw layer is optional.

For some (valid) reasons, the NAF specification stops with sent attribute (sentence id of the token) in wf (word form) element. While reading an NAF document, I find it tough to de-tokenize i.e. reconstructing the sentence text. A simple concatenation won't do, as different parsers tokenize in different ways. The following implementation will be useful.

Under Constants
```
    # Raw layer
    RAW_LAYER_TAG = "raw"
```
Under __init__
```
        raw_layer = self.tree.find(self.RAW_LAYER_TAG)
        if raw_layer is not None and len(raw_layer):
            self.raw = raw_layer
        else:
            self.raw = etree.SubElement(self.root, self.RAW_LAYER_TAG)
```
New method
```
    def add_raw(self, sentences, separator):
        """Add a Raw layer to the KAF file.

        :param sentences: List of sentences.
        """
        if self.raw is None:
            self.raw = etree.SubElement(self.root, self.RAW_LAYER_TAG)

        self.raw.text = etree.CDATA(separator.join(sentences))	# To be able to split the text back into sentences
```

**Comment by ragerri** [comment]
Hello,

Can you do a PR?

R

**Comment by jofatmofn** [comment]
Sorry for this noob comment (Infact I googled to understand what you meant by "PR"). In "Pull requests" tab, when I clicked "New pull request" button, I got "Compare changes" screen. Here the "Create pull request" button was enabled only when "base" branch was "duplicatedheaders" and "compare" branch was "master". For other 3 combinations it was disabled. I went ahead and created pull request. But the descriptions such as "jofatmofn wants to merge 1 commit into duplicatedheaders from master" and "Merge pull request #1 from ixa-ehu/duplicatedheaders" in that Conversation page make me think that my request is inappropriate.

**Comment by ragerri** [comment]
Hello,

You need to fork the repo, and then open a PR from the forked repo.

https://help.github.com/articles/about-collaborative-development-models/
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Thanks!

Rodrigo

**Comment by josubg** [comment]
I just merged a new version that includes your feature. 

The feature not include the sentence separation mechanic you suggested  because a segmentation is more advanced concept that a raw text. However, with the implemented mechanics you can still make the  `separator.join(sentences)` outside the lib. 

Please check it if fits your needs and thanks for your feedback
